name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Sync to HF
        uses: huggingface/hub-sync@v1.0
        with:
          github_repo_id: shwetanksinghrajput/resume-analyzer
          huggingface_repo_id: shwetaaank/RESUME-ANALYZER
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
